tracker:
  frame_rate: 30
  match_thresh: 0.8
  track_buffer: 20
  trajectory_retention: 60
yolo:
  classes:
  - can
  - hand
  confidence_threshold: 0.3
  iou_threshold: 0.45
  model_path: v2_yolov8n_HERMASA_finetune.pt
