# YOLO model configuration
yolo:
  model: "v2_yolov8n_HERMASA_finetune.pt"
  model_path: "v2_yolov8n_HERMASA_finetune.pt"
  confidence_threshold: 0.30
  iou_threshold: 0.45
  image_size: [416, 416]
  classes: ["can", "hand"]

# Tracker configuration
tracker:
  track_buffer: 150
  trajectory_retention: 50