version: "3.8"
services:
  calippo:
    build:
      context: ..
      dockerfile: gentl/Dockerfile
    container_name: calippo_yolo
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/app:rw
    working_dir: /app
    network_mode: host
    ipc: host
    privileged: true
    command: ["python3", "gentl/PruebaAravis.py"]
